### ISSUE TITLE
我是用你的yolov7_demo.py文件，然后将model_type换成yolov7hub，结果报错.

### ISSUE THREAD

**Issue by Hehezcr** [kadirnar/Yolov7-SAHI#7]
Traceback (most recent call last):
  File "D:/001Study/Mycode/Yolov7-SAHI-main/yolov7_demo.py", line 20, in <module>
    result = get_sliced_prediction(
  File "D:\001Study\Mycode\Yolov7-SAHI-main\sahi\predict.py", line 239, in get_sliced_prediction
    prediction_result = get_prediction(
  File "D:\001Study\Mycode\Yolov7-SAHI-main\sahi\predict.py", line 91, in get_prediction
    detection_model.perform_inference(np.ascontiguousarray(image_as_pil))
  File "D:\001Study\Mycode\Yolov7-SAHI-main\sahi\models\yolov7hub.py", line 41, in perform_inference
    raise ValueError("Model is not loaded, load it by calling .load_model()")
ValueError: Model is not loaded, load it by calling .load_model()

**Comment by kadirnar** [comment]
Can you share your code?

**Comment by Hehezcr** [comment]
>谢谢，我找到原因了。我路径没写对，现在可以了，感谢您给的代码提供参考。

**Comment by kadirnar** [comment]
Thank you for the feedback.
